### ISSUE TITLE
subscribeDatapoint does not work with method updateDatapointWithID

### ISSUE THREAD

**Issue by aloha99** [aconaframework/acona#7]
subscribeDatapoint erstellt kein ID für die Funktion und somit werden die subscribed Werte nicht angezeigt, weil es kein Mapping gibt. Workaround: Verwende nur „addManagedDatapoints“. Minor

Solution: If there is no ID, the datapoint address shall be the ID. All datapoints shall be passed.

**Comment by aconaframework** [comment]
fixed in the MQTT version
