### ISSUE TITLE
Subscribehandler uses agent name inconsistenly

### ISSUE THREAD

**Issue by aloha99** [aconaframework/acona#8]
In SubscriptionHandler kommen Adressen mit beide Agent als auch ohne Agent vor. Es sollen nur Namen ohne Agent oder mit Agent vorkommen. Das Problem wurde durch das vervollständigen der Adressen in subscribe korrigiert.

**Comment by aconaframework** [comment]
Fixed in the new MQTT-Version by automatic extension of the name
