### ISSUE TITLE
Function Trigger during function run are not considered

### ISSUE THREAD

**Issue by aloha99** [aconaframework/acona#9]
Codelet Handlers sollen 2 Mal triggern falls sie getriggert werden während sie laufen. Dies ist jetzt nicht der Fall und somit muss man auf Timings aufpassen, jedoch soll ein Handler nur einmal getriggert werden können, d.h. wenn 10 trigger kommen, soll er trotzdem nur einmal ausführen.

**Comment by aconaframework** [comment]
Fixed through test echoExecutionOfFunctionOnValueUpdate()

	/**
	 * This command is reset as the start is triggered. It is used if a start
	 * command is triggered, while the thread is already running. In that case,
	 * the system shall run again to be up to date.
	 */
	protected boolean startCommandIsSet = false;

This switch can be set through configuration depending on the mode.
